"""Clean RokomariBG books, steps S1-S6 of docs/10-cleaning-spec.md.

Usage:  python -m scripts.clean.rokomari_books
Input:  data/raw/rokomaribg/book.json.gz
Output: data/interim/rokomari_books.parquet
        docs/reports/cleaning-s1-s6.md   (rows changed per rule, class counts)
"""
import gzip
import json
import time
from pathlib import Path

import pandas as pd

from scripts.clean import text as T

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw" / "rokomaribg" / "book.json.gz"
OUT = ROOT / "data" / "interim" / "rokomari_books.parquet"
REPORT = ROOT / "docs" / "reports" / "cleaning-s1-s6.md"


def load():
    with gzip.open(RAW, "rt", encoding="utf-8") as fh:
        return pd.DataFrame(json.load(fh))


def main():
    t0 = time.time()
    stats = {}
    df = load()
    stats["raw_rows"] = len(df)

    # S1: deduplicate. Strip "Show More" first so the longest-summary rule sees real lengths.
    df["summary_raw"] = df.book_summary
    df["_s"] = df.book_summary.map(T.strip_show_more)
    df["_len"] = df._s.str.len()
    df["_filled"] = df.notna().sum(axis=1)
    df["dup_count"] = df.groupby("book_id").book_id.transform("size")
    df = df.sort_values(["_len", "_filled"], ascending=False)
    df = df.drop_duplicates("book_id").sort_values("book_id", key=lambda s: s.astype(int))
    stats["unique_books"] = len(df)
    stats["books_with_duplicates"] = int((df.dup_count > 1).sum())
    stats["show_more_stripped"] = int(df.summary_raw.fillna("").str.contains(T.SHOW_MORE).sum())

    # S2 + S5: titles
    df["title_raw"] = df.book_title
    titles = pd.DataFrame(df.book_title.map(T.clean_title).tolist(), index=df.index)
    df = pd.concat([df, titles], axis=1)
    stats["title_changed"] = int((df.title_clean != df.title_raw).sum())
    for col in ["binding", "paper", "volume", "series_hint", "language_hint"]:
        stats[f"title_{col}_extracted"] = int(df[col].notna().sum())
    stats["title_is_bundle"] = int(df.is_bundle.sum())
    stats["title_is_collection"] = int(df.is_collection.sum())

    # S2: summary text
    t1 = time.time()
    df["summary_norm"] = df._s.map(T.clean_text)
    stats["summary_normalize_seconds"] = round(time.time() - t1, 1)
    stats["summary_changed_by_normalisation"] = int(
        (df.summary_norm.fillna("") != df._s.fillna("")).sum())

    # S3: fields
    isbn = df.isbn.map(T.normalize_isbn)
    df["isbn13"] = isbn.str[0]
    df["isbn_valid"] = isbn.str[1]
    df["isbn_origin"] = df.isbn13.map(T.isbn_origin)
    stats["isbn_present"] = int(df.isbn.notna().sum())
    stats["isbn_valid"] = int(df.isbn_valid.sum())
    stats["isbn10_converted"] = int((df.isbn.map(T.isbn_digits).str.len() == 10).sum())
    df["pages"] = pd.to_numeric(df.book_pages.astype(str).map(T.bn_digits_to_ascii), errors="coerce")
    df.loc[df.pages <= 0, "pages"] = pd.NA
    for col in ("rating_count", "review_count"):
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    df["rating_avg"] = pd.to_numeric(df.average_rating, errors="coerce")
    df.loc[(df.rating_count == 0) | ~df.rating_avg.between(1, 5), "rating_avg"] = pd.NA
    stats["rating_set_to_null"] = int(df.rating_avg.isna().sum())

    # S4: script
    df["title_script"] = df.title_clean.map(T.script_of)
    df["summary_script"] = df.summary_norm.map(T.script_of)

    # S6: summary classes
    cls = df.summary_norm.map(T.classify_summary)
    df["summary_class"] = cls.str[0]
    df["summary_clean"] = cls.str[1]
    df["summary_len"] = df.summary_clean.fillna("").str.len()
    df["summary_usable"] = [T.summary_usable(c, s) for c, s in zip(df.summary_class, df.summary_clean)]
    stats["summary_class_counts"] = df.summary_class.value_counts().to_dict()
    stats["summary_usable"] = int(df.summary_usable.sum())

    keep = ["book_id", "dup_count", "title_raw", "title_clean", "binding", "paper", "volume", "series_hint",
            "language_hint", "is_bundle", "is_collection", "title_script", "summary_raw", "summary_norm", "summary_clean", "summary_class",
            "summary_len", "summary_usable", "summary_script", "isbn", "isbn13", "isbn_valid", "isbn_origin",
            "pages", "rating_avg", "rating_count", "review_count", "category_id", "author_id",
            "publisher_id", "book_url"]
    out = df[keep].rename(columns={"isbn": "isbn_raw", "category_id": "primary_category_id",
                                   "author_id": "primary_author_id"})
    OUT.parent.mkdir(parents=True, exist_ok=True)
    out.to_parquet(OUT, index=False)
    stats["seconds_total"] = round(time.time() - t0, 1)

    lines = ["# Cleaning report: RokomariBG books, S1–S6", "",
             "Generated by `python -m scripts.clean.rokomari_books`. Spec: [10-cleaning-spec.md](../10-cleaning-spec.md).", "",
             "| Metric | Value |", "|---|---|"]
    for k, v in stats.items():
        if k != "summary_class_counts":
            lines.append(f"| {k} | {v:,} |" if isinstance(v, int) else f"| {k} | {v} |")
    lines += ["", "## Summary classes", "| Class | Books |", "|---|---|"]
    lines += [f"| {k} | {v:,} |" for k, v in stats["summary_class_counts"].items()]
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(out):,} rows) and {REPORT} in {stats['seconds_total']}s")


if __name__ == "__main__":
    main()
