"""Profile the RokomariBG dataset and write a markdown report.

Usage:  python scripts/profile_rokomaribg.py
Input:  data/raw/rokomaribg/*.json.gz
Output: docs/reports/rokomaribg-profile.md
"""
import gzip
import json
import re
from collections import Counter
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw" / "rokomaribg"
OUT = ROOT / "docs" / "reports" / "rokomaribg-profile.md"

# Rokomari category names are in English. Keyword match, case-insensitive.
FICTION_KEYWORDS = ["novel", "story", "stories", "fiction", "thriller", "mystery", "detective",
                    "horror", "adventure", "fantasy", "romance", "romantic", "humor", "comics",
                    "children & teens", "fairy", "folk tale", "উপন্যাস", "গল্প"]
POETRY_KEYWORDS = ["poem", "poetry", "rhyme", "কবিতা"]
TRANSLATION_KEYWORDS = ["translat", "অনুবাদ"]
SHOW_MORE = r"\s*Show More\s*$"


def load(name):
    with gzip.open(RAW / f"{name}.json.gz", "rt", encoding="utf-8") as fh:
        return pd.DataFrame(json.load(fh))


def isbn_country(isbn):
    """Registration group from the ISBN: 984 = Bangladesh, 81/93 = India."""
    if not isinstance(isbn, str):
        return "missing"
    digits = re.sub(r"[^0-9Xx]", "", isbn)
    if len(digits) == 13 and digits.startswith(("978", "979")):
        digits = digits[3:]
    elif len(digits) != 10:
        return "malformed"
    if digits.startswith("984"):
        return "bangladesh"
    if digits.startswith(("81", "93")):
        return "india"
    return "other"


def pct(n, total):
    return f"{n:,} ({n / total:.1%})" if total else "0"


def main():
    books = load("book")
    authors = load("author")
    cats = load("category")
    pubs = load("publisher")
    b2c = load("book_to_category")
    b2a = load("book_to_author")
    reviews_link = load("book_to_review")

    lines = ["# RokomariBG profile", "",
             "Generated by `scripts/profile_rokomaribg.py`. Numbers describe the raw dataset before cleaning.", ""]
    add = lines.append

    # --- Rows and IDs ---
    n_rows, n_ids = len(books), books.book_id.nunique()
    books["book_summary"] = books.book_summary.fillna("").str.replace(SHOW_MORE, "", regex=True).str.strip()
    dup_rows = books[books.duplicated("book_id", keep=False)]
    # Repeated IDs are the same book scraped more than once; keep the row with the longest summary.
    books_u = (books.assign(_len=books.book_summary.str.len())
               .sort_values("_len", ascending=False)
               .drop_duplicates("book_id").drop(columns="_len"))
    add("## 1. Rows and IDs")
    add(f"- Rows in book.json: **{n_rows:,}**; unique `book_id`: **{n_ids:,}**")
    add(f"- Rows that share a `book_id` with another row: {len(dup_rows):,} "
        f"in {dup_rows.book_id.nunique():,} groups")
    if len(dup_rows):
        same = dup_rows.groupby("book_id").agg(t=("book_title", "nunique"), u=("book_url", "nunique"))
        add(f"- Groups with identical title and URL: {(same.t.eq(1) & same.u.eq(1)).mean():.1%}. "
            "These are repeated scrapes, deduplicated by keeping the longest summary.")
    add("")

    # --- Titles ---
    t = books_u.book_title.fillna("")
    suffix = t.str.extract(r"(\([^)]*\))\s*$")[0].dropna()
    add("## 2. Titles")
    add(f"- Titles ending in a parenthetical: {pct(len(suffix), n_ids)}")
    add("- Most common trailing parentheticals:")
    for s, c in suffix.value_counts().head(12).items():
        add(f"  - `{s}`: {c:,}")
    has_latin = t.str.contains(r"[A-Za-z]")
    has_bangla = t.str.contains(r"[ঀ-৿]")
    add(f"- Bangla-script titles: {pct(int(has_bangla.sum()), n_ids)}; Latin-only: {pct(int((has_latin & ~has_bangla).sum()), n_ids)}")
    ta = books_u.merge(b2a.drop_duplicates("book_id"), on="book_id", how="left", suffixes=("", "_link"))
    key = ta.book_title.str.replace(r"\s*\([^)]*\)\s*$", "", regex=True).str.strip() + "|" + ta.author_id.astype(str)
    dup_key = key.duplicated(keep=False)
    add(f"- Books sharing (title without suffix + author) with another book, likely editions or duplicates: {pct(int(dup_key.sum()), n_ids)}")
    add("")

    # --- Summaries ---
    s = books_u.book_summary
    lens = s.str.len()
    add("## 3. Summaries (`book_summary`)")
    add("- The trailing 'Show More' scraper artifact (present on ~99.7% of rows) is stripped before measuring.")
    add(f"- Empty or null: {pct(int((lens == 0).sum()), n_ids)}")
    for lo, hi in [(1, 200), (200, 500), (500, 1500), (1500, 10**9)]:
        add(f"- {lo}–{hi if hi < 10**9 else '∞'} chars: {pct(int(((lens >= lo) & (lens < hi)).sum()), n_ids)}")
    add(f"- Median length (non-empty): {int(lens[lens > 0].median()):,} chars")
    patterns = {
        "flap-text prefix (…ফ্ল্যাপ-এর লেখা)": r"ফ্ল্যাপ",
        "'সূচিপত্র' (table of contents)": r"সূচিপত্র",
        "'ভূমিকা' / 'মুখবন্ধ' (preface)": r"ভূমিকা|মুখবন্ধ",
        "'সংক্ষিপ্ত বিবরণ' / 'সারসংক্ষেপ'": r"সংক্ষিপ্ত বিবরণ|সারসংক্ষেপ",
        "mostly Latin script (>50% A–Z)": None,
        "contains URL": r"https?://",
    }
    for label, pat in patterns.items():
        if pat is None:
            latin_share = s.str.count(r"[A-Za-z]") / lens.clip(lower=1)
            n = int(((latin_share > 0.5) & (lens > 50)).sum())
        else:
            n = int(s.str.contains(pat, regex=True).sum())
        add(f"- {label}: {pct(n, n_ids)}")
    add("")

    # --- Categories ---
    cat_name = cats.set_index("category_id").category_name
    b2c_u = b2c.drop_duplicates()
    b2c_u = b2c_u[b2c_u.book_id.isin(books_u.book_id)]
    b2c_u["name"] = b2c_u.category_id.map(cat_name)
    per_book = b2c_u.groupby("book_id").name.apply(list)
    add("## 4. Categories")
    add(f"- Categories: {len(cats):,}; book–category links: {len(b2c_u):,}; "
        f"median categories per book: {per_book.str.len().median():.0f}")

    def any_kw(names, kws):
        return any(k.lower() in str(n).lower() for n in names for k in kws)

    fiction = per_book.apply(lambda n: any_kw(n, FICTION_KEYWORDS))
    poetry = per_book.apply(lambda n: any_kw(n, POETRY_KEYWORDS))
    transl = per_book.apply(lambda n: any_kw(n, TRANSLATION_KEYWORDS))
    add(f"- Books with a fiction-like category (keyword match): {pct(int(fiction.sum()), n_ids)}")
    add(f"- Books with a poetry-like category: {pct(int(poetry.sum()), n_ids)}")
    add(f"- Books with a translation-like category: {pct(int(transl.sum()), n_ids)}")
    add("- Top 40 categories by book count:")
    for name, c in b2c_u.name.value_counts().head(40).items():
        add(f"  - {name}: {c:,}")
    add("")

    # --- Origin via ISBN ---
    origin = books_u.isbn.apply(isbn_country)
    add("## 5. Origin signal from ISBN")
    for k, c in origin.value_counts().items():
        add(f"- {k}: {pct(int(c), n_ids)}")
    fic_ids = set(per_book[fiction].index)
    fo = origin[books_u.book_id.isin(fic_ids)].value_counts()
    add(f"- Among fiction-like books: " + ", ".join(f"{k} {v:,}" for k, v in fo.items()))
    add("")

    # --- Publishers ---
    add("## 6. Publishers")
    pc = books_u.publisher_id.map(pubs.set_index("publisher_id").publisher_name).value_counts()
    add(f"- Publishers with at least one book: {len(pc):,}")
    add("- Top 20 publishers:")
    for name, c in pc.head(20).items():
        add(f"  - {name}: {c:,}")
    india_pubs = books_u[origin == "india"].publisher_id.map(pubs.set_index("publisher_id").publisher_name).value_counts()
    add("- Top 15 publishers of India-ISBN books:")
    for name, c in india_pubs.head(15).items():
        add(f"  - {name}: {c:,}")
    add("")

    # --- Authors ---
    an = authors.author.fillna("").str.strip()
    add("## 7. Authors")
    add(f"- Author rows: {len(authors):,}; unique `author_id`: {authors.author_id.nunique():,}")
    dup_names = an[an.duplicated(keep=False) & (an != "")]
    add(f"- Author names shared by more than one ID: {dup_names.nunique():,} names ({len(dup_names):,} IDs)")
    add(f"- With bio: {pct(int(authors.bio.notna().sum()), len(authors))}")
    add(f"- Names in Bangla script: {pct(int(an.str.contains(r'[ঀ-৿]').sum()), len(authors))}")
    per_book_authors = b2a.drop_duplicates().groupby("book_id").size()
    add(f"- Books with more than one author link: {pct(int((per_book_authors > 1).sum()), n_ids)}")
    add("")

    # --- Reviews ---
    rc = reviews_link.groupby("book_id").size()
    add("## 8. Reviews")
    add(f"- Review links: {len(reviews_link):,}; books with at least 1 review text: {len(rc):,}")
    add(f"- Books whose `review_count` > 0 (on Rokomari): {int((books_u.review_count.fillna(0) > 0).sum()):,}. "
        "The dataset holds review text for only a subset.")
    for k in [5, 10, 50]:
        add(f"- Books with ≥{k} reviews: {int((rc >= k).sum()):,}")
    fic_int = {int(x) for x in fic_ids if str(x).isdigit()}
    add(f"- Fiction-like books with ≥5 reviews: {int(rc[rc.index.isin(fic_int)].ge(5).sum()):,}")
    add("")

    # --- Candidate first catalogue ---
    good_summary = lens >= 200
    cand = books_u[good_summary.values & books_u.book_id.isin(fic_ids).values]
    add("## 9. Candidate first catalogue")
    add(f"- Fiction-like books with a summary of at least 200 chars: **{len(cand):,}**")
    add(f"- … and with ISBN origin india: {int((cand.isbn.apply(isbn_country) == 'india').sum()):,}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
